### ISSUE TITLE
Seznam rails hostingů

### ISSUE THREAD

**Issue by kepi** [csrug/csrug.github.com#2]
Na úvodní straně je nepravdivě napsáno, že u nás neexistují jiné rails hostingy než rubyonrails.cz

Byl bych rád za přidání http://www.ruby-hosting.cz/ každopádně nechtěl jsem posílat přímo pull request, protože existuje např. i g-hosting.cz a možná se najdou ještě další. Nebylo by tedy dobré udělat stránku hostingům přímo dedikovanou a připsat tam i nějaké info? Nebo zatím pokud jsou jen tyhle tři tak je nechat pouze na úvodní straně?

**Comment by karmi** [comment]
Ruby-hosting.cz ani G-Hosting neznáme, nevíme, nikdy se neúčastnili komunitních akcí. Nevíme, kolik aplikací, jakých a zda vůbec umějí provozovat.

Proto v _žádném případě_ takové "hostingy" na stránky _Rubyonrails.cz_ dávat nebudeme. Až se ukáže, že "jiné rails hostingy" opravdu umějí hostovat Rails, až se ukáže, jak to dělají, co hostují, atd. atd., pak se budeme bavit.

**Comment by kepi** [comment]
Jak se taková věc ukáže? Samozřejmě máte právo spravovat si vaši stránku jak je libo, příjde mi jen velmi nevhodné psát na úvodní stránce něčeho, co se tváří jako komunitní projekt, nepravdivou informaci.

V každém případě co takhle navrhnout, jakým způsobem lze tedy ukázat, že jiné hostingy opravu umí hostovat rails, jakým způsobem ukázat, jak to dělají? Nechci toto řešit nijak individuálně pro náš hosting, rád bych, aby všichni měli tu šanci a aby se vytvářelo rozumné a konkurenční prostředí, ze kterého mohou participovat všichni railsaři u nás.

**Comment by karmi** [comment]
Nevím, co je "váš" hosting, nikdy jsem nebyl svědkem, že by jakýkoliv český hosting aktivně propagoval Rails, byl schopen prokázat, že Ruby a Rails rozumí, a můžeme ho s klidným svědomím na _Rubyonrails.cz_ doporučit.

Tak do toho!

**Comment by karmi** [comment]
Jen pro doplnění: informace

> ... jiné hostingy specializované na Rails u nás (prozatím) neexistují ...

ani zdaleka není nepravdivá. Pokud existuje v ČR/SR hosting **specializovaný** na Rails, ať se ozve, plus viz výše...

**Comment by kepi** [comment]
Náš hosting je ruby-hosting.cz a věřím, že Rails rozumíme a umíme, jelikož v něm děláme opravdu dlouho, popravdě jsme rails hostovali dříve než railshosting.cz, pouze jsme to dělali jen pro pár zákazníků a nikde nepropagovali.

V každém případě to o co mi jde je právě to, abych věděl, podle jakých kritérií určujete, co je a není ruby on rails hosting dle vašich kritérií, protože doposud jsem si myslel, že pokud někdo dělá vše v Railsech, Rails hostuje a aktivně vylepšuje své technologie, může se nazývat specializovaným Rails hostingem. Netušil jsem, že musí uspořádat konferenci, protože do té doby není technicky kvalifikovaný na to být hostingem :) Vůbec mě prosím neberte nijak zle, opravdu se jen snažím zjistit v čem je problém, ale dostává se mi od vás odpovědí, které mi příjdou jendoduše takové, že se tím nechcete zabývat a hlavně mě rychle odbýt (možná se ale pletu).

Jinak opravdu jsme zatím neuspořádali žádnou rails konferenci a když už jsme na nějaké byly, neměli jsme vyvěšeny své banery. Aktivně se zapojujeme do dění okolo brněnské ruby user grup (www.brug.cz) a již dlouhá léta se snažíme o osvětu Railsů u svých obchodních partnerů, známých a ostatních.

Ještě jednou ale zopakuji, že mi jde především o to, aby byly jasné obecné kritéria pro to jak být zařazen na stránky komunitního? www.rubyonrails.cz pro všechny.

**Comment by kepi** [comment]
Ještě kdyžtak uvedu naši drobnou publikační činnost na http://blog.igloonet.cz/rubriky/vyvoj-aplikaci/ruby-on-rails/ plus jsme kromě akcí brug.cz přednášeli o Ruby on Rails na brněnské Internet Session (http://www.session-brno.cz/)

**Comment by karmi** [comment]
Tak to zkusme takhle:

1/ Ruby-hosting.cz existuje už pár let, nikdy jsme o nich nic neslyšeli, nevíme kdo tam hostuje, nevíme co to umí. Zkuste „komunitu” přesvědčit, že je to jinak.

2/ Na igloonet vidím tři obecné články o Rails.

Formální kritéria pro „zařazení na stránky”, pokud se bavíme o _hostingu_, nejsou. Přesvědčte komunitu, že si zasloužíte tam být -- naříkáním to nebude.

(Mimochodem: věřím, že tvrzení „ popravdě jsme rails hostovali dříve než railshosting.cz“ je lež jen z neznalosti :)

**Comment by kepi** [comment]
Obecně věta "věřím.." bude těžko lží, když tomu opravdu věřím :) Začali jsme s hostingem railsů chvíli po tom, co se Rails jako takové vůbec objevily a pamatuji si novinku, že je spuštěn railshosting.cz až v nějaké době po té. Nikdy jsme ale neřešili žádný marketing a navíc opravdu si nepamatuji žádná data, takže jako kdybych nic neřekl, nemám a nechci to nijak prokazovat ani se o takové prvenství vůbec prát :)

add 1/ ok, nebudeme to řešit. Netuším, co je to komunita ve vašem pojetí, protože minimálně v naší společnosti komunita lidí ohledně Rails je a stejně tak v Brně, ale to asi není ta komunita o které mluvíte, zřejmě myslíte tu na irc, kde minimálně já nejsem. Určitě tam nechci přijít a tlačit náš hosting nebo někoho přesvědčovat, zajímalo mě pozadí toho jak funguje přidávání na rubyonrails.cz což jsem se nedozvěděl. Věřím, že výsledný commit a publikaci na stránce není spuštěn nějakým obecným hlasováním, ale dle nějakých principů.

add 2/ ano, psal jsem drobnou publikační činnost...

V každém případě díky za odpovědi, i když v negativním duchu. Tlačit na irc náš hosting nebo se ptát lidí tam, jak se dostat na stránku jsem rozhodně nechtěl. Nechci se nikde nacpat stůj co stůj, jen mě zajímaly principy.

Větu s naříkáním myslíte vážně? Založil jsem před 7 měsíci ticket, nikde jsem nenaříkal, pouze jsem se zeptal.

**Comment by karmi** [comment]
Ad 1/ ohledně "prvenství" prostě věřím, že lžete, ale domnívám se, že lžete jen z neznalosti.

Ad 2/ jsem se nedozvěděl zas nic já od vás, jen nějaké naříkání.

Ad 3/ bez komentáře.

**Comment by simi** [comment]
Prosím o znovu otevření tohoto tiketu a o dohodě na zveřejnění nestranného seznamu služeb nabízených v ČR. Pro začátek můžeme vycházet z http://www.jakpsatweb.cz/katalog/hosting-ror.html. 

_To co předvedlo tehdejší vedení CSRUG tady je fakt ostuda._

**Comment by iNecas** [comment]
Z komunitného hľadiska si myslím, ze uvádzať na stránkach komunity jednu konkrétnu hostingovú firmu s trvdením, že nič iné tu aj tak nie je, nie je úplne dobré: dajme tomu že by som chcel začať s RoR v roku 2014: tak sa pozreim, ako je na tom český rubysta a dozviem sa akurát to, že za posledné 3 roky v ČR po RoR nikto ani neštekol.

Na druhej strane, keby som mal hostingovú firmu a povedal by som si, že českí rubysti si zaslúžia profesionálny hosting (a možno by som aj zaplatil nejakého railsového špecialistu, aby mi s tým pomohol), pozriem na túto diskuziu a utekám kade ľahšie.

Takže aby sme to tu trochu vyžehlili, zástupcov z uvedených skupín: Ruby a Railsy v ČR žije, aj keď možno nie na csrug.

**Comment by karmi** [comment]
@iNecas Doporuceni hostingu s klidem odstranime, pred 2 roky byla skutecne takova, ze _specializovane_ hostingy na Rails neexistovaly. Jak je to dnes se neodvazuji soudit.

**Comment by kubicek** [comment]
@simi žádné jiné než "tehdejší" vedení není.

Souhlasím se zrušením odkazu na konkrétní hosting.

**Comment by simi** [comment]
Tak to jsem netušil. Nehodlám se hádat o dva roky starých zprávách.

Každopádně mi nejde o zrušení stávajícího odkazu, ale naopak o přidání více odkazů. Railshosting.cz si podle mne odkaz na webu určitě zaslouží.

Pro začátek by stačilo asi umazat "neboť jiné hostingy specializované na Rails u nás (prozatím) neexistují". A pokud někdo dorazí s doporučením na další hostingy, proč je nepřidat. Schválně jich zkusím pár kontaktovat a optat se, zda-li není možnost testu zdarma. Pak ale bude záležet, jestli moje doporučení bude mít nějákou váhu, protože stejně se tak může stát, že dopadnu jako @kepi.

**Comment by iNecas** [comment]
Ono bude vždy ťažké rozhodovať sa, či si ten alebo onen hosting zaslúži, aby bol uvedený na týchto stránkach alebo nie, Osobne by som bol asi veľmi nerád v pozícii toho, kto o tom rozhoduje.
Preto chápem odstránenie tejto rubriky z hlavnej stránky a súhlasím s tým.

Na druhej strane si viem predstaviť jednoduchú službu, kde by mohli užívateľia zdielať svoje dojmy s rôznych hostingov a bol by odkaz práve na túto službu. Netuším, či už niečo také existuje, ale ak nie, v záujme podpory komunity by na tom mohla trebárs zapracovať nejaká hostingovka (ktorej ide koniec koncov o zisk, tak prečo tomu nepomôcť, a kľudne si môže niekde do rohu dať logo "Powered by XYZ", open-source výhodou až nutnosťou :)
