### ISSUE TITLE
Job board

### ISSUE THREAD

**Issue by roolo** [csrug/csrug.github.com#3]
Bylo by pekne mit na ror.cz stranku s nabidkou a poptavkou prace.

Prijde mi, ze se u nas rails rozjizdi dost vlazne, tak by se tomu trochu pomohlo :)

**Comment by karmi** [comment]
Prosím, diskuse na IRC nebo Google Group.

**Comment by karmi** [comment]
BTW: OMFG, "u nas rails rozjizdi dost vlazne" -- co tohleto je za kravinu? Rails se u nás "vlažně" rozjíždí už pár let, a na to jak "vlažně" se rozjíždí, tak to docela sviští.

**Comment by roolo** [comment]
To "vlazne" vychazi z toho, ze pracuju ve firme, kde shanime ruby vyvojare a zatim tu byl na pohovor jeden. Na napriklad php, nebo js chodi minimalne jeden tydne. Pokud to svisti, tak nekde okolo nas. 

Presouvam se s komunikaci na IRC
